### ISSUE TITLE
set-url 錯誤

### ISSUE THREAD

**Issue by pczheng** [seLain/ghsp2ofer#1]
錯誤訊息
```
Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v origin
  stderr: 'fatal: unable to access 'https://pczheng:Gsdasf%e#aasdf&ddk3@github.com/pc
zheng/wondaponda.git/': Port number ended with 'G''
```
密碼是錯誤時的密碼      目前已修改

**Comment by seLain** [comment]
How about removing `#` from your password ?

**Comment by pczheng** [comment]
把 #  & 都移掉  改變成認證問題  但密碼是正確的
```
  stderr: 'fatal: Authentication failed for 'https://pczheng:Gsdasf%eaasdfddk3@gith
ub.com/pczheng/wondaponda.git/''
```

**Comment by seLain** [comment]
Might be credential issue, refs:
* [stackoverflow: git-credential-helper-update-password](https://stackoverflow.com/questions/25845963/git-credential-helper-update-password)
* [how-to-update-your-git-credentials-on-windows] (https://cmatskas.com/how-to-update-your-git-credentials-on-windows/)

**Comment by pczheng** [comment]
可以了
