### ISSUE TITLE
commit author name "xxx" if executed by administrator

### ISSUE THREAD

**Issue by Pyrrhadile** [seLain/ghsp2ofer#6]
If the bot.py executed by administrator in command line, the commit author will not be that set in `settings.py`. Instead it shows `xxx`.

example :  **xxx add files: p1tr.plugins.textutils.TextutilsPlugin.html p1tr.lib.core…  …**

it should be: **Pyrrhadile add files: p1tr.plugins.textutils.TextutilsPlugin.html p1tr.lib.core…  …**

**Comment by ladykiki** [comment]
同样的情况...跑了程序几天没数字
关掉重新跑就可以

**Comment by seLain** [comment]
@Pyrrhadile 
It seems that there is no git author configuration in your `Administrator` account. There is two solutions:
#### Solution 1: do not use Administrator in executing bot.py
Just use your user account to open command line and execute bot.py
#### Solution 2: set specific account/mail for each repository
Using `git --global` to set account/mail in each repository ( for example, in  `cloned_repos\xxxx_repo`).
Check out more detailed instructions on [Github help](https://help.github.com/articles/setting-your-commit-email-address-in-git/)

This issue will be marked `won't fix` unless there is something specific we can do.
